# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:

# General
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-illegal-windows-names
    -   id: check-toml
    -   id: check-yaml
        args:
            - --allow-multiple-documents
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

# Python
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.6.9
  hooks:
    - id: ruff # Run the linter.
    - id: ruff-format # Run the formatter.

# Verilog
-   repo: local
    hooks:
    -   id: system
        name: verible-verilog-format
        entry: verible-verilog-format
        language: system
        files: \.sv$
        args:
            # - --column_limit=120
            # - --indentation_spaces=2
            # - --wrap_spaces=4
            - --inplace
            - --assignment_statement_alignment=flush-left
            - --case_items_alignment=flush-left
            - --class_member_variable_alignment=flush-left
            - --distribution_items_alignment=flush-left
            - --enum_assignment_statement_alignment=flush-left
            - --formal_parameters_alignment=flush-left
            - --module_net_variable_alignment=flush-left
            - --named_parameter_alignment=flush-left
            # - --named_parameter_indentation=indent
            - --port_declarations_alignment=flush-left
            # - --port_declarations_indentation=indent
            - --struct_union_members_alignment=flush-left
            - --wrap_end_else_clauses=1

-   repo: local
    hooks:
    -   id: system
        name: verible-verilog-lint
        entry: verible-verilog-lint
        language: system
        files: \.sv$
        # args:
        #     - --line-length=120

# C/C++
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v19.1.7
    hooks:
    -   id: clang-format
        files: \.(c|h|cc|cpp|hpp)$

# Markdown
- repo: https://github.com/executablebooks/mdformat
  rev: 0.7.17
  hooks:
  - id: mdformat
    # Optionally add plugins
    additional_dependencies:
    - mdformat-gfm
    # - mdformat-beautysh
